# Generated by Django 4.1.13 on 2024-04-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(max_length=50)),
                ('collegeAddress', models.CharField(max_length=50)),
                ('collegeState', models.CharField(max_length=50)),
                ('collegeCity', models.CharField(max_length=50)),
                ('collegePhoneNumber', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'SCM_COLLEGE',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('courseDescription', models.CharField(max_length=100)),
                ('courseDuration', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SCM_COURSE',
            },
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('maths', models.IntegerField()),
            ],
            options={
                'db_table': 'SCM_MARKSHEET',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=50)),
                ('subjectDescription', models.CharField(max_length=50)),
                ('course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_manage.course')),
            ],
            options={
                'db_table': 'SCM_SUBJECT',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examTime', models.CharField(max_length=40)),
                ('examDate', models.DateField()),
                ('semester', models.CharField(max_length=50)),
                ('course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_manage.course')),
                ('subject_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_manage.subject')),
            ],
            options={
                'db_table': 'SCM_TIMETABLE',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('college_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_manage.college')),
            ],
            options={
                'db_table': 'SCM_STUDENT',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('college_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_manage.college')),
                ('course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_manage.course')),
                ('subject_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_manage.subject')),
            ],
            options={
                'db_table': 'SCM_FACULTY',
            },
        ),
    ]
