version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SCM
      MYSQL_USER: root1
      MYSQL_PASSWORD: root1
    volumes:
      - db_data:/var/lib/mysql  # Persist data in a named volume
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql  # Optional: Initialize with SQL
    ports:
      - "3307:3306"  # Expose MySQL on port 3307 on the host

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/SCM
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: